import type { Metadata } from "next";
import "@repo/ui/globals.css";
import "@radix-ui/themes/styles.css";
import { AppProvider } from "../context/AppProvider";
import { Theme } from "@radix-ui/themes";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Theme>
          <AppProvider>
            {children}
          </AppProvider>
        </Theme>
      </body>
    </html>
  );
}
