import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { AppProvider } from "../context/AppProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
